//
//  Constants.m
//  DDayReminder
//
//  Created by 모근원 on 11. 11. 16..
//  Copyright (c) 2011년 __MyCompanyName__. All rights reserved.
//

#import "Constants.h"


int const _TAB_BAR_ITEM_DIC = 90001;
int const _TAB_BAR_ITEM_WORD = 90002;
int const _TAB_BAR_ITEM_SETTING = 90003;

int const _AD_NO = 0;
int const _AD_IAD = 80001;
int const _AD_ADAM = 80002;

NSString* const _NOTIFICATION_SHOW_DIC_KEYBOARD = @"NOTI_SHOW_DIC_KEYBOARD";
NSString* const _NOTIFICATION_PASTE_FROM_CLIPBOARD = @"NOTI_PASTE_FROM_CLIPBOARD";



NSString* const _NOTIFICATION_HIDE_AD = @"NOTI_HIDE_AD";
NSString* const _NOTIFICATION_SHOW_AD = @"NOTI_SHOW_AD";
NSString* const _NOTIFICATION_ORIENTATION_CHANGE = @"NOTI_ORIENTATION_CHANGE";

NSString* const _NOTIFICATION_HIDE_TAB_BAR = @"NOTIFICATION_HIDE_TAB_BAR";
NSString* const _NOTIFICATION_SHOW_TAB_BAR = @"NOTIFICATION_SHOW_TAB_BAR";

NSString* const _NOTIFICATION_FINISH_READ_DIC_FILE = @"NOTIFICATION_FINISH_READ_DIC_FILE";
NSString* const _NOTIFICATION_FINISH_SEARCH = @"NOTIFICATION_FINISH_SEARCH";

//NSString* const _NOTIFICATION_SHOW_DELETE_ALL_BUTTON = @"NOTIFICATION_SHOW_DELETE_ALL_BUTTON";
//NSString* const _NOTIFICATION_HIDE_DELETE_ALL_BUTTON = @"NOTIFICATION_HIDE_DELETE_ALL_BUTTON";
